#数据库连接池
spring:
# 格式化日期
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.yidiandian.entity

#服务端口
server:
  port: 8762

#注册中心地址[多个配置中心，中间用逗号分开]
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/ # ,http://127.0.0.1:8762/eureka/


